### ISSUE TITLE
Assemble java examples

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j-examples-java#1]
We currently have three distinct repositories that all contain examples of neow3j using Java (this repository, [spring-boot-examples](https://github.com/neow3j/neow3j-examples-java-spring-boot) and [java-android](https://github.com/neow3j/neow3j-examples-java-android)).
To keep a clear overview of our Java example projects, these could be assembled in one repository.

**Comment by gsmachado** [comment]
@mialbu @csmuller I haven't tested the Android examples yet, so, I will leave this open.

However, I think we can delete the git repos [neow3j-examples-java-spring-boot](https://github.com/neow3j/neow3j-examples-java-spring-boot) and [neow3j-examples-java-android](https://github.com/neow3j/neow3j-examples-java-android). Can you confirm, @mialbu, that all the code was already copied?

**Comment by csmuller** [comment]
After discussion with @mialbu, i deleted the repos neow3j-examples-java-spring-boot and neow3j-examples-java-android.

**Comment by mialbu** [comment]
Can I close this issue or is there anything more to assemble? @csmuller and @gsmachado

**Comment by gsmachado** [comment]
Yes. Nothing else to be discussed. Closing.
