### ISSUE TITLE
Example of a Smart Contract that calls another Smart Contract method

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j-examples-java#15]
Create an example of a `contract A` that calls a specific `contract B` method.

It can be called `CallAnotherContract.java`.

**Comment by gsmachado** [comment]
I know we have, e.g., the `NonDivisibleNFToken`, that has a `Contract.call()` already ([see here](https://github.com/neow3j/neow3j-examples-java/blob/master/neo-n3-examples/src/main/java/io/neow3j/examples/contractdevelopment/contracts/NonDivisibleNFToken.java#L107)). But, maybe a more explicit and simpler Smart Contract with that feature would be nice -- since it's key for the development of more elaborate examples.

**Comment by mialbu** [comment]
This was added in commit 8a3d092.
