### ISSUE TITLE
How to cancel the vote ？

### ISSUE THREAD

**Issue by bxlkm** [neow3j/neow3j-examples-java#17]
please help me ths！

**Comment by gsmachado** [comment]
Hello @bxlkm

Can you please tell me more?

Would you like that we create a Java example using [neow3j](https://github.com/neow3j/neow3j) to cancel a vote?

**Comment by bxlkm** [comment]
@gsmachado Yes, examples of canceling voting and withdrawing awards。ths！！！

**Comment by gsmachado** [comment]
@bxlkm you can find an example on how to vote for a pubKey candidate [in this file](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractinvoke/VoteForValidator.java#L56-L67).

If you would like to withdraw GAS, you just need to make a GAS transfer to another Neo address. You can find an example [here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractinvoke/TransferGas.java).

If you want to check the GAS balance of your wallet, you can use the `GasToken` class (check the available methods).

**Comment by gsmachado** [comment]
@mialbu any example on how to cancel a vote?

Correct me if I'm wrong, but to cancel a vote someone could simply give `null` to the "candidateKey" param on the `.vote()` method [here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractinvoke/VoteForValidator.java#L56)... right?

**Comment by csmuller** [comment]
@bxlkm, to cancel a vote do this with neow3j:
```java
        NeoSendRawTransaction response = new NeoToken(neow3j)
                .invokeFunction("vote", hash160(account.getScriptHash()), any(null))
                .signers(AccountSigner.calledByEntry(account))
                .sign()
                .send();
```

**Comment by bxlkm** [comment]
@csmuller @mialbu thank you very much！

**Comment by bxlkm** [comment]
@csmuller @mialbu  How to write the GAS Claim code？

**Comment by csmuller** [comment]
You can do it by transferring any amount of NEO to yourself. In the example below, a transfer from `account` to itself is made assuming that its balance is 1 or higher.

```java
        new NeoToken(neow3j).transfer(account, account.getScriptHash(), BigInteger.ONE)
                .sign()
                .send();
```

**Comment by bxlkm** [comment]
@csmuller ths。

**Comment by gsmachado** [comment]
@bxlkm I will close this issue. If any questions remain, please re-open it. Thanks! 👍
