### ISSUE TITLE
getBalance can return null

### ISSUE THREAD

**Issue by qvanphong** [neow3j/neow3j-examples-java#20]
In FungibleToken example:
https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/FungibleToken.java

there is a [getBalance](https://github.com/neow3j/neow3j-examples-java/blob/386128df99c0de3ecae4475b328951d9b4b00bfd/src/main/java/io/neow3j/examples/contractdevelopment/contracts/FungibleToken.java#L153) method that return a current balance of address passed in. But in most cases, their balance does not exist yet and cause that the `assetMap.getInteger` will return null. Which gonna lead to "Specified cast is not valid" when invoking `transfer`.

I would recommend change `getBalance` to:
```java
	private static int getBalance(Hash160 account) {
		Integer balance = Storage.getInteger(sc, account.toByteArray());
		return balance != null ? balance : 0;
	}
```

**Comment by gsmachado** [comment]
Hello @qvanphong
Maybe, could the `getBalance` you proposed return `Boolean`? DId you test it?

**Comment by qvanphong** [comment]
> Hello @qvanphong Maybe, could the `getBalance` you proposed return `Boolean`? DId you test it?

`getBalance` that I proposed will always return int, if the data does not exist in DB yet, it will return 0.

since `getBalance` from example will return null if data doesn't exist, I have written a simple test to check if Storage.getInteger really returns null in that case, and yes, it will.

**Comment by csmuller** [comment]
Thanks @qvanphong for pointing this out. It is definitely better to check for null in the `getBalance` method before returning. I will adapt the example. In the future we will provide a `getInteger` method that already does that internally (changes in PR https://github.com/neow3j/neow3j/pull/702).
