### ISSUE TITLE
nep-11 demo 

### ISSUE THREAD

**Issue by jack9684** [neow3j/neow3j-examples-java#21]
i found there are some nonfungibletoken contracts on neo-n3-examples. 

is there any demo ,how to invoke the function according to java neo3j , like invoke the mint function with parameter ,and recieve prpoerties function value from the demo NonFungibleToken.java contract?

**Comment by gsmachado** [comment]
Hello @jack9684 

Thanks for trying neow3j. 🎉 

You can find docs in many places! 🎉  Including our website https://neow3j.io.

But, I think it would be nice if you take a look at [this specific example](https://github.com/neow3j/neow3j-examples-java/blob/ca4acc5d3086d806f05e2e30ab152407cc8aac9e/src/main/java/io/neow3j/examples/contractinvoke/CreateMultiInvokeTransaction.java) -- which is an example to create a single transaction with multiple invokes in it to `mint` a token.

This file is located in this [same repository](https://github.com/neow3j/neow3j-examples-java), in the [`contractinvoke`](https://github.com/neow3j/neow3j-examples-java/tree/master/src/main/java/io/neow3j/examples/contractinvoke) directory.

Please, close the issue if this solved your problem/question. 👍

**Comment by gsmachado** [comment]
@jack9684 any news?

**Comment by jack9684** [comment]
@gsmachado  thank  u ,very much  . is there  any demo about recive public static Map<String, String> properties(ByteString tokenId) result,in java ? and is there some mistake on  DivisibleNonFungibleToken.java  :

private static void addToOwnersTokens(Hash160 owner, ByteString tokenId) {
        new StorageMap(ctx, createTokensOfPrefix(owner)).put(tokenId, tokenId);
    }

    private static void removeOwnersToken(Hash160 owner, ByteString tokenId) {
        new StorageMap(ctx, createTokensOfPrefix(owner)).put(tokenId, tokenId);
    }
at line 180,and 184.  i think removeOwnersToken should me delete it from createTokensOfPrefix(owner)s StorageMap?

**Comment by mialbu** [comment]
> [...] is there some mistake on DivisibleNonFungibleToken.java :
> 
> private static void addToOwnersTokens(Hash160 owner, ByteString tokenId) { new StorageMap(ctx, createTokensOfPrefix(owner)).put(tokenId, tokenId); }
> 
> ```
> private static void removeOwnersToken(Hash160 owner, ByteString tokenId) {
>     new StorageMap(ctx, createTokensOfPrefix(owner)).put(tokenId, tokenId);
> }
> ```
> 
> at line 180,and 184. i think removeOwnersToken should me delete it from createTokensOfPrefix(owner)s StorageMap?

@jack9684, yes, you are correct. It's a mistake, it should be `delete`. I've just pushed a commit that fixes that.

**Comment by mialbu** [comment]
> @gsmachado thank u ,very much . is there any demo about recive public static Map<String, String> properties(ByteString tokenId) result,in java ? [...]

@jack9684 There's currently no example in this repo, but you can check out the code in the `NonFungibleToken` wrapper in neow3j [here](https://github.com/neow3j/neow3j/blob/590495615e164737035021cd20953c62fe7ef187/contract/src/main/java/io/neow3j/contract/NonFungibleToken.java#L407-L417).

**Comment by jack9684** [comment]
thank u very much ~
