### ISSUE TITLE
NonFungibleToken demo about tokensOf method called by  io.neow3j.contract.NonFungibleToken  at  version 3.16.0

### ISSUE THREAD

**Issue by jack9684** [neow3j/neow3j-examples-java#22]
i foud there are some  convenience method  at  io.neow3j.contract.NonFungibleToken to invoke the contract at nep11
when the contract code in  NonFungibleToken  demo like this
```java
public static Iterator<ByteString> tokensOf(Hash160 owner) {
        return (Iterator<ByteString>) Storage.find(
                ctx.asReadOnly(), createTokensOfPrefix(owner), FindOptions.RemovePrefix);
    }
```
then i call it use io.neow3j.contract.NonFungibleToken  at  version 3.16.0
```java
Hash160 contractHash = new Hash160("xxxxxxxx");
NonFungibleToken nft = new NonFungibleToken(contractHash,NEOW3J);
List<byte[]> bytes = nft.tokensOf(cj.getScriptHash());
 ```
it throw exceptions:
```
Exception in thread "main" io.neow3j.protocol.exceptions.StackItemCastException: Cannot cast stack item Struct{value='ByteString{value='01'}, ByteString{value='01'}'} to a byte array.
```
it looks like the type did not match.
the method gived by io.neow3j.contract.NonFungibleToken can not uesd . i have to write some another codes  to run.

is it good way to supprot  this method?

**Comment by mialbu** [comment]
@jack9684 The example contract did not contain the `FindOption.KeysOnly`. I have pushed the fix in the commit https://github.com/neow3j/neow3j-examples-java/commit/96f132f2c8d29bb139135e4ae449feaebfd962f2. Thanks for pointing it out.
