### ISSUE TITLE
Create examples on how to use neow3j NeoFS SDK

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j-examples-java#23]
Container

- [x] Create a container
- [x] Delete a container
- [x] Get container
- [x] List containers

Object
- [x] Create a file
- [x] Get a file
- [x] Delete a file

Accounting
- [x] Get account's NeoFS balance

Netmap
- [x] Get NeoFS netmap information

**Comment by mialbu** [comment]
Done (5a9399590c3fa25dd4c57fad35300a201bef599e)
