### ISSUE TITLE
Create a contract example that functions as a trust

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j-examples-java#37]
The goal is to imitate a simple trust fund. In such a fund, the trustor transfers assets to a trustee, who holds the assets for the benefit of a third party called the beneficiary. The trustor defines rules on when and why the assets in the fund can be used by the beneficiary. The trustee is the "middle-man" that enforces the rules, e.g., only pays out the assets to the beneficiary once the trustor is dead.

The goal here is to implement a Neo smart contract (called "trust" from here on) with Java and neow3j that performs the functions of the trustee.

User Stories to cover:
- As a trustor I want to transfer crypto assets to trust and configure a beneficiary who can gain access to the assets.
- As a trustor I want to be able to set a multi-sig account as the beneficiary such that multiple people have to come together to get access to funds.
- As a trustor I want to establish rules on when (e.g., block height) and in which amounts the beneficiary can get access to the assets.
- As a trustor I want to configure if I can regain control over the assets, i.e., if it assets are revocable.
- As a beneficiary I want claim assets that are in the trust and belong to me.

The intention of this issue is that you get familiar with Neo and neow3j by using it instead of immediately workin on the code base itself.
Use the [boilerplate repo](https://github.com/neow3j/neow3j-boilerplate-contracts) that gives you a boilerplate project setup for contract development with neow3j. The [neow3j docs](https://neow3j.io/#/) should be your friend in the process, especially the [smart contract development](https://neow3j.io/#/neo-n3/smart_contract_development/introduction) part.

**Comment by gsmachado** [comment]
What's the state of this issue?

Did you chat with @mialbu and now it's clearer what needs to be adapted here? Please, let's finish this asap.

The [PR](https://github.com/neow3j/neow3j-examples-java/pull/38) needs to be adapted, IMHO.

**Comment by thedanielmark** [comment]
@gsmachado Yes I had a meeting with Michael and some updates have been made to the PR. I believe it can be closed after @mialbu pushes the latest version.

@mialbu could you please push the latest changes to this branch? 😃

**Comment by mialbu** [comment]
> What's the state of this issue?
> 
> Did you chat with @mialbu and now it's clearer what needs to be adapted here? Please, let's finish this asap.
> 
> The [PR](https://github.com/neow3j/neow3j-examples-java/pull/38) needs to be adapted, IMHO.

We had a good call about it. I think I could provide some useful inputs that will help update the PR, e.g.,

- introduce an `Arbitor`
- use a `Hash160` as beneficiary
- move the logic of `createAgreement` to be executed in the `OnNep17Payment` method
- create a function `executeAgreement` that has some restrictions, e.g., only be callable from the Arbitor or some time restrictions.

**Comment by mialbu** [comment]
@thedanielmark I don't have time to test the code we've written in our call. So, I can push some changes I still have locally, but then please adapt it a bit further and update the code in the class `Escrow` where you're invoking the contract. There you could create two examples, one `EscrowCreateAgreement`, and another one `EscrowExecuteAgreement`.

**Comment by thedanielmark** [comment]
@mialbu sure, I'll look into adapting it further.

**Comment by mialbu** [comment]
I've pushed the code. @thedanielmark I've added some todos and notes (see `EscrowExampleCreateTrustAgreement.java`).

**Comment by mialbu** [comment]
Done in #38 (and #39)
