### ISSUE TITLE
changing magic number and key type in 3.7.0

### ISSUE THREAD

**Issue by djm34** [neow3j/neow3j-examples-java#9]
Hello,

I would like to know how to change the magic numer and the address key type in the version 3.7.0
the method neoconfig seems to have disappeared.

Thanks for your help,

**Comment by djm34** [comment]
ok found it :D

**Comment by gsmachado** [comment]
@djm34 next time, can you please open issues at the main neow3j repository https://github.com/neow3j/neow3j ? Thanks!
